version: "3.8"
services:
  client:
    container_name: gamenight-client
    build:
      context: ./client
      dockerfile: dev.dockerfile
    stdin_open: true
    env_file:
      - ./client/.docker.env
    volumes:
      - ./client:/app
    ports:
      - ${DEV_CLIENT_PORT}:4000
    networks:
      - frontend

  server:
    container_name: gamenight-server
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - ./server:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    env_file:
      - ./server/.docker.env
    ports:
      - ${DEV_SERVER_PORT}:4001
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: developmentpassword
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - ${DEV_MONGOUI_PORT}:4002
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: developmentpassword
      VCAP_APP_PORT: 4002
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
