version: "3.8"
services:
  client:
    container_name: gamenight-client
    build:
      context: ./client
      dockerfile: dev.dockerfile
    stdin_open: true
    env_file:
      - ./client/.docker.env
    volumes:
      - ./client:/app
    ports:
      - 4000:4000
    networks:
      - frontend

  server:
    container_name: gamenight-server
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - ./server:/app
    working_dir: /app
    env_file:
      - ./server/.env
    ports:
      - 4001:4001
      - 9229:9229
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: developmentpassword
    ports:
      - 27017:27017
    networks:
      - backend
    logging:
      driver: none

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - 4002:4002
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: developmentpassword
      VCAP_APP_PORT: 4002
    networks:
      - frontend
      - backend
    logging:
      driver: none

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
