name: Linter

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: github/super-linter@v2.0.0
      env:
        VALIDATE_ALL_CODEBASE: false
